openapi: 3.0.2
info:
  title: API for compile server
  description: "GET request return the version of given compiler (interpreter), \n\
    POST request requires an UUID of user from Firebase Authentication\n"
  version: 1.0.0-oas3
servers:
- url: https://online-code-exercise.herokuapp.com
paths:
  /java:
    summary: Access to java compiler
    get:
      summary: return java and javac version
      responses:
        "200":
          description: Return the output of command 'java -version',
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "500":
          description: Unexpected Error
    post:
      summary: Test code with given input and expected output
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        "200":
          description: Code was compiled or run successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "500":
          description: The test failed to compile or had syntax error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
      security:
      - BearerAuth: []
components:
  schemas:
    inline_response_200_1_results:
      type: object
      properties:
        passed:
          type: boolean
          description: whether the test is passed or not
          example: true
        input:
          type: string
          description: The content passed into stdin stream
          example: 1 2
        expected:
          type: string
          description: The expected output
          example: "3"
        actual:
          type: string
          description: The content which program wrote to stdout stream
          example: "3"
    inline_response_200_1:
      type: object
      properties:
        total:
          type: number
          description: The total number of test cases
          example: 10
        passed:
          type: number
          description: The number of tests passed
          example: 6
        failed:
          type: number
          description: The number of tests failed
          example: 4
        failedIndexes:
          type: array
          description: The positions of failed tests
          items:
            type: number
        results:
          type: array
          description: The result of each test
          items:
            $ref: '#/components/schemas/inline_response_200_1_results'
      description: The result of the test
    inline_response_500_error:
      properties:
        name:
          type: string
          description: an error type, which is usually a shell error
          example: ChildProcessError
        code:
          type: integer
          description: |
            Exit code, [see this Stackoverflow answer](https://unix.stackexchange.com/a/254747)
          example: 1
        childProcess:
          type: object
          description: this object is not used
          example: {}
        stdout:
          type: string
          description: output written to stdout stream, always an empty string
          example: ""
        stderr:
          type: string
          description: error message written to stderr stream
    inline_response_200:
      type: object
      properties:
        message:
          type: string
          example: "openjdk version \"11.0.9.1\" 2020-11-04\nOpenJDK Runtime Environment\
            \ (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)\nOpenJDK 64-Bit Server VM (build\
            \ 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing) , \n"
    java_testcases:
      type: object
      properties:
        input:
          type: string
          description: The content to pass into stdin stream
          example: 1 2
        output:
          type: string
          description: The content expected to be written to stdout stream
          example: "3"
    body:
      type: object
      properties:
        code:
          type: string
          description: The code to test
          example: import java.util.Scanner;public class Program{public static void
            main(String[]args){Scanner reader=new Scanner(System.in);int a=reader.nextInt();int
            b=reader.nextInt();System.out.println(a+b);reader.close();}},
        testcases:
          type: array
          description: Contains serveral test cases which will be used to test the
            given code
          items:
            $ref: '#/components/schemas/java_testcases'
    inline_response_500:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/inline_response_500_error'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
