name: deploy app to heroku using docker
on:
  push:
    tags:
      - v0.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{39c0ec27-bd06-4097-99f9-fd01811d971e}}
          heroku_app_name: 'online-code-exercise'
          heroku_email: 'azerprojects@gmail.com'
          usedocker: true
